# Shared for all services

# access actuator endpoints without requiring authentication
management:
  security:
    enabled: false
    
eureka:
  instance:
    prefer-ip-address:  true
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka
  

# zipkin base url 
spring:    
  zipkin:
    base-url: http://zipkin-service:9411/
  

 
# Token storage        
oauth2-db:        
  datasource:
    url: jdbc:mysql://db_oauth2:3306/oauth2
    username: root
    password: '{cipher}084bc27633e111321a8f2aa0e670ba040c0a07fd9b594bc03d93c67205831ef6'
    driver-class-name: com.mysql.jdbc.Driver
    dbcp: # Keep the connection alive if idle for a long time (needed in production)
      test-while-idle: true
      validation-query: SELECT 1