server:
  port: ${port:9999}


  # User authentication database
spring:        
  datasource:
    url: jdbc:mysql://192.168.168.58:3307/kms
    username: root
    password: '{cipher}c0e640a37211ad21c3e207930a51cb9ad8d4ca8183035d62ed46ecdb16dea1dd08191060c6dede54d72883ec227d9a4d'   
    driver-class-name: com.mysql.jdbc.Driver
    dbcp: # Keep the connection alive if idle for a long time (needed in production)
      test-while-idle: true
      validation-query: SELECT 1