server:
  port: ${port:8082}

message: Hello World User Service !! Default Profile !!

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_user
    username: root
    password: '{cipher}084bc27633e111321a8f2aa0e670ba040c0a07fd9b594bc03d93c67205831ef6'
    dbcp: # Keep the connection alive if idle for a long time (needed in production)
      test-while-idle: true
      validation-query: SELECT 1
  jpa:
    show-sql: true # Show or not log for each sql query
    hibernate:
      ddl-auto: update # Hibernate ddl auto (create, create-drop, update)     
      naming:
        implicit-strategy:  org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

logging:
  config: https://raw.githubusercontent.com/kcouk/uksims-config/master/user-service-default-logback.xml
  file: user-service/user-service.log
  level:
    root: warn
    co.uk.kuwait: debug

#logging:
#  level:
#    co.uk.kuwait.mailservice.MessageRestController: debug
#    org.hibernate.type.descriptor.sql: trace
#    org.hibernate.sql: debug


# Use spring.jpa.properties.* for Hibernate native properties (the prefix is
# stripped before adding them to the entity manager)

# The SQL dialect makes Hibernate generate better SQL for the chosen database
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect



#    5am every day
purge.cron.expression: 0 0 5 * * ?



################### JavaMail Configuration ##########################
#support.email: johnnymerayo@gmail.com
#spring.mail.host: smtp.gmail.com
#spring.mail.port: 465
#spring.mail.protocol: smtps
#spring.mail.username: johnnymerayo@gmail.com
#spring.mail.password: *********
#spring.mail.properties.mail.transport.protocol: smtps
#spring.mail.properties.mail.smtps.auth: true
#spring.mail.properties.mail.smtps.starttls.enable: true
#spring.mail.properties.mail.smtps.timeout: 8000

